/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as CreateMatchIdRouteImport } from './routes/create.$matchId'
import { Route as CardSubmissionIdRouteImport } from './routes/card.$submissionId'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMatchIdRoute = CreateMatchIdRouteImport.update({
  id: '/create/$matchId',
  path: '/create/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CardSubmissionIdRoute = CardSubmissionIdRouteImport.update({
  id: '/card/$submissionId',
  path: '/card/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/card/$submissionId': typeof CardSubmissionIdRoute
  '/create/$matchId': typeof CreateMatchIdRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/card/$submissionId': typeof CardSubmissionIdRoute
  '/create/$matchId': typeof CreateMatchIdRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/card/$submissionId': typeof CardSubmissionIdRoute
  '/create/$matchId': typeof CreateMatchIdRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/card/$submissionId'
    | '/create/$matchId'
    | '/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/card/$submissionId'
    | '/create/$matchId'
    | '/match/$id'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/card/$submissionId'
    | '/create/$matchId'
    | '/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  CardSubmissionIdRoute: typeof CardSubmissionIdRoute
  CreateMatchIdRoute: typeof CreateMatchIdRoute
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$matchId': {
      id: '/create/$matchId'
      path: '/create/$matchId'
      fullPath: '/create/$matchId'
      preLoaderRoute: typeof CreateMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$submissionId': {
      id: '/card/$submissionId'
      path: '/card/$submissionId'
      fullPath: '/card/$submissionId'
      preLoaderRoute: typeof CardSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  CardSubmissionIdRoute: CardSubmissionIdRoute,
  CreateMatchIdRoute: CreateMatchIdRoute,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
